#!/usr/bin/env ruby
#^syntax detection
# encoding: utf-8

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git'
cookbook 'git', :git => 'https://github.com/fnichol/chef-git.git'

