#!/usr/bin/env ruby
#^syntax detection
# encoding: utf-8

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git'
cookbook 'ruby_build', :github => 'fnichol/chef-ruby_build', :ref => 'v0.7.2'
cookbook 'postgresql', :github => 'express42-cookbooks/postgresql'
